### ISSUE TITLE
v2.6.2 not available through composer

### ISSUE THREAD

**Issue by therealgilles** [rollbar/rollbar-php-wordpress#104] opened 2021-12-05 20:20 UTC
I am getting the following error while trying to install v2.6.2:

```
  Problem 1
    - Root composer.json requires wpackagist-plugin/rollbar ^2.6.2, found wpackagist-plugin/rollbar[dev-trunk, 1.0.0, ..., 1.0.4, 2.0.0, ..., 2.6.1] but it does not match the constraint.
```

**Comment by bishopb** [comment] 2021-12-06 22:49
Thanks for the report, @therealgilles. [WordPress packagist][1] just mirrors the WordPress plugin and theme directories as a Composer repository, and (because of Issue 98) we don't yet have the WordPress plugin directory updated. (You may notice that the [latest version is 2.6.1][2] on the WordPress plugin page.)

When Issue #98 has resolved, and we have the latest version at WordPress, then WordPress packagist will see it.  In the meantime, you may consider [downloading and installing the release manually][1], or temporarily pinning to 2.6.1.

I'm closing this as a duplicate of Issue #98, but feel free to re-open if you'd like to continue the conversation.

[1]:https://wpackagist.org
[2]:https://wordpress.org/plugins/rollbar/
[3]:https://github.com/rollbar/rollbar-php-wordpress/releases/tag/v2.6.2

**Closed by bishopb** 2021-12-06 22:49 UTC
